name: CineScope
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2
dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  dio: ^5.11.1
  get_it: ^9.2.1
  flutter_bloc: ^9.1.1
  flutter_native_splash: ^2.4.8
  flutter_offline: ^6.0.0
  skeleton_shimmer: ^1.2.2
  pretty_dio_logger: ^1.4.0
  flutter_launcher_icons: ^0.14.4
  firebase_core: ^3.12.0
  firebase_auth: ^5.5.1
  google_sign_in: ^6.2.2
  shared_preferences: ^2.5.5
  google_fonts: ^8.2.1
  envied: ^0.5.4+1



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0
  build_runner: ^2.4.0
  envied_generator: ^0.5.0




flutter:


  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

flutter_native_splash:
  color: "#0B0B12"
  image: "assets/icons/icon_logo.png"
  android_12:
    color: "#0B0B12"
    image: "assets/icons/icon_logo.png"
flutter_launcher_icons:
  android: true
  image_path: "assets/icons/icon_logo.png"